# Generated by Django 5.0.6 on 2024-05-21 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Фамилия Имя Отчество')),
                ('date', models.DateTimeField(verbose_name='Дата заезда')),
                ('departure', models.DateTimeField(verbose_name='Дата выезда')),
                ('full_text', models.TextField(verbose_name='Дополнительные пожелания')),
            ],
        ),
    ]
